<?php
/**
 * Implementation of hook_menu().
 */
function menufun_menu() {
  $items['menufun'] = array(
    'title' => 'Redeem',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('menufun_form'),
    'access callback' => TRUE,
    'type' => MENU_NORMAL_ITEM,
);
  return $items;
}

/**
 * Page callback.
 */
function menufun_hello() {
  return t('Hello!');
}

/**
  * Define the form
  */
function menufun_form() {
  $form['voucher_id'] = array(
    '#title' => t('Your Name'),
    '#type' => 'textfield',
    '#description' => t('Please enter your name.'),
  );
$form['submit'] = array(
  '#type' => 'submit',
  '#value' => t('Submit')
);

return $form;
}
/**
* Validate the form.
*/
function menufun_form_validate($form, &$form_state) {
if ($form_state['values']['voucher_id'] == NULL ) {
  // We notify the form API that this field has failed validation.
  form_set_error('voucher_id',
    t('Please enter a voucher number!'));
}
}
/**
* Handle post-validation form submission.
*/
function menufun_form_submit($form, &$form_state) {
$id_number = $form_state['values']['voucher_id'];
drupal_set_message(t('Voucher %id_number has been redeemed!',
  array('%id_number' => $id_number)));
  $options = array('query' => array('$id_number' => $id_number));
drupal_goto('node/%', $options);
}
